
--UPDATE 20180317
USE QLTHUVIEN
CREATE TABLE NHAXUATBAN(
MANXB CHAR(10) PRIMARY KEY,
TENNXB NVARCHAR(50),
DIACHI NVARCHAR(50),
SDT CHAR(11))



ALTER TABLE SACH DROP COLUMN NHAXUATBAN
ALTER TABLE SACH ADD MANXB CHAR(10) REFERENCES NHAXUATBAN(MANXB)

--
CREATE TABLE NGONNGU(
MANN CHAR(10) PRIMARY KEY,
NGONNGU NVARCHAR(50))
ALTER TABLE SACH DROP COLUMN NGONNGU
ALTER TABLE SACH ADD MANN CHAR(10) REFERENCES NGONNGU(MANN)

